### ISSUE TITLE
Attempted to beginRule: MultiRule[], does not match outer scope rule: R/

### ISSUE THREAD

**Issue by basilevs** [eclipse-rcptt/org.eclipse.rcptt#60]
Following error happens when creating AUT:
```
eclipse.buildId=4.31.0.I20240229-0520
java.version=17.0.10
java.vendor=Private Build
BootLoader constants: OS=linux, ARCH=aarch64, WS=gtk, NL=en
Command-line arguments:  -os linux -ws gtk -arch aarch64 -data file:/home/ubuntu/rcptt_workspace/

org.eclipse.core.jobs
Error
Thu Mar 28 10:19:06 UTC 2024
An internal error occurred during: "Re-resolve Target state after VM-Install or EE change".

java.lang.IllegalArgumentException: Attempted to beginRule: MultiRule[], does not match outer scope rule: R/
	at org.eclipse.core.runtime.Assert.isLegal(Assert.java:68)
	at org.eclipse.core.internal.jobs.ThreadJob.illegalPush(ThreadJob.java:144)
	at org.eclipse.core.internal.jobs.ThreadJob.push(ThreadJob.java:416)
	at org.eclipse.core.internal.jobs.ImplicitJobs.begin(ImplicitJobs.java:88)
	at org.eclipse.core.internal.jobs.JobManager.beginRule(JobManager.java:341)
	at org.eclipse.core.internal.resources.WorkManager.checkIn(WorkManager.java:124)
	at org.eclipse.core.internal.resources.Workspace.prepareOperation(Workspace.java:2398)
	at org.eclipse.core.internal.resources.Project$1.run(Project.java:601)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2448)
	at org.eclipse.core.internal.resources.Project.internalBuild(Project.java:642)
	at org.eclipse.core.internal.resources.Project.build(Project.java:162)
	at org.eclipse.pde.internal.core.MinimalState.reloadSystemPackagesIntoState(MinimalState.java:339)
	at org.eclipse.pde.internal.core.MinimalState$2.runInWorkspace(MinimalState.java:312)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:43)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by basilevs** [comment]
The bug is fixed in PDE and will hopefully reach 2024-06

**Comment by basilevs** [comment]
Fixed in https://github.com/eclipse-pde/eclipse.pde/pull/1216
