### ISSUE TITLE
Bug 568677: Execution hangs after openning Preferences dialog

### ISSUE THREAD

**Issue by basilevs** [eclipse-rcptt/org.eclipse.rcptt#64]
[Original bug 568677](https://bugs.eclipse.org/bugs/show_bug.cgi?id=568677)
### Test steps
Run a test:

```
get-preferences-menu | click
get-window Preferences | get-tree | select "General/Network Connections"
```
### Actual result
It hangs on second command

```
"main" #1 prio=6 os_prio=31 cpu=834346.59ms elapsed=868.24s tid=0x0000000131809200 nid=0x103 runnable  [0x000000016d0b1000]
   java.lang.Thread.State: RUNNABLE
	at java.lang.StackTraceElement.initStackTraceElements(java.base@17.0.4.1/Native Method)
	at java.lang.StackTraceElement.of(java.base@17.0.4.1/StackTraceElement.java:541)
	at java.lang.Throwable.getOurStackTrace(java.base@17.0.4.1/Throwable.java:839)
	- locked <0x00000007f23d3ba0> (a java.lang.Exception)
	at java.lang.Throwable.getStackTrace(java.base@17.0.4.1/Throwable.java:831)
	at java.lang.Thread.getStackTrace(java.base@17.0.4.1/Thread.java:1610)
	at org.eclipse.rcptt.tesla.swt.aspects.DisplayAspect.getRunnableName(DisplayAspect.aj:482)
	at org.eclipse.rcptt.tesla.swt.aspects.DisplayAspect.ajc$inlineAccessMethod$org_eclipse_rcptt_tesla_swt_aspects_DisplayAspect$org_eclipse_rcptt_tesla_swt_aspects_DisplayAspect$getRunnableName(DisplayAspect.aj:1)
	at org.eclipse.rcptt.tesla.swt.aspects.DisplayAspect.ajc$around$org_eclipse_rcptt_tesla_swt_aspects_DisplayAspect$15$241be8f4(DisplayAspect.aj:440)
	at org.eclipse.swt.widgets.Display.timerExec_aroundBody20(Display.java:5323)
	at org.eclipse.swt.widgets.Display$AjcClosure21.run(Display.java:1)
	at org.eclipse.rcptt.sherlock.aspects.swt.DisplayAspect.ajc$around$org_eclipse_rcptt_sherlock_aspects_swt_DisplayAspect$4$45c2b55fproceed(DisplayAspect.aj:98)
	at org.eclipse.rcptt.sherlock.aspects.swt.DisplayAspect.ajc$around$org_eclipse_rcptt_sherlock_aspects_swt_DisplayAspect$4$45c2b55f(DisplayAspect.aj:124)
	at org.eclipse.swt.widgets.Display.timerExec(Display.java:5323)
	at org.eclipse.oomph.ui.ButtonAnimator.run(ButtonAnimator.java:98)
	at org.eclipse.rcptt.sherlock.core.SherlockTimerRunnable.run(SherlockTimerRunnable.java:23)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	- locked <0x00000007f23d1f78> (a org.eclipse.swt.widgets.RunnableLock)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4365)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3988)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open_aroundBody0(Window.java:799)
	at org.eclipse.jface.window.Window.open(Window.java:785)
	at org.eclipse.ui.internal.handlers.ShowPreferencePageHandler.execute_aroundBody0(ShowPreferencePageHandler.java:58)
	at org.eclipse.ui.internal.handlers.ShowPreferencePageHandler$AjcClosure1.run(ShowPreferencePageHandler.java:1)
	at org.eclipse.rcptt.tesla.recording.aspects.WorkbenchRecordingAspect.ajc$around$org_eclipse_rcptt_tesla_recording_aspects_WorkbenchRecordingAspect$2$943c663bproceed(WorkbenchRecordingAspect.aj:55)
	at org.eclipse.rcptt.tesla.recording.aspects.WorkbenchRecordingAspect.ajc$around$org_eclipse_rcptt_tesla_recording_aspects_WorkbenchRecordingAspect$2$943c663b(WorkbenchRecordingAspect.aj:67)
	at org.eclipse.ui.internal.handlers.ShowPreferencePageHandler.execute(ShowPreferencePageHandler.java:47)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute_aroundBody0(HandlerProxy.java:277)
	at org.eclipse.ui.internal.handlers.HandlerProxy$AjcClosure1.run(HandlerProxy.java:1)
	at org.eclipse.rcptt.tesla.recording.aspects.WorkbenchRecordingAspect.ajc$around$org_eclipse_rcptt_tesla_recording_aspects_WorkbenchRecordingAspect$2$943c663bproceed(WorkbenchRecordingAspect.aj:55)
	at org.eclipse.rcptt.tesla.recording.aspects.WorkbenchRecordingAspect.ajc$around$org_eclipse_rcptt_tesla_recording_aspects_WorkbenchRecordingAspect$2$943c663b(WorkbenchRecordingAspect.aj:67)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:271)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:98)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@17.0.4.1/Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@17.0.4.1/NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@17.0.4.1/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java.base@17.0.4.1/Method.java:568)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:298)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:232)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:174)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:165)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:485)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:204)
	at org.eclipse.ui.internal.handlers.LegacyHandlerService.executeCommand(LegacyHandlerService.java:385)
	at org.eclipse.ui.internal.handlers.LegacyHandlerService.executeCommand(LegacyHandlerService.java:362)
	at org.eclipse.rcptt.tesla.internal.ui.processors.SWTUIProcessor$10.run(SWTUIProcessor.java:2679)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	- locked <0x00000007e4970c40> (a org.eclipse.swt.widgets.RunnableLock)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4365)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3988)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1042)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:152)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:639)
	at org.eclipse.ui.internal.Workbench$$Lambda$275/0x0000000800f4ab60.run(Unknown Source)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:546)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:173)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:143)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:109)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:439)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:271)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@17.0.4.1/Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@17.0.4.1/NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@17.0.4.1/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java.base@17.0.4.1/Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1459)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1432)
```
Hypothesis - Display.sleep() is never called in this scenario, resulting in idle Tesla processors.

**Comment by basilevs** [comment]
Preferences window is not opened in an AUT, when it is launched from sources. Even if recording and replay are inactive.

**Comment by basilevs** [comment]
Following path is not executed in AUT:
```
Thread [main] (Suspended (breakpoint at line 572 in MenuItem))	
	MenuItem.sendSelection() line: 572	
	Display.windowProc(long, long) line: 6096	
	OS.objc_msgSendSuper(objc_super, long, long, long, long, boolean) line: not available [native method]	
	Display.applicationNextEventMatchingMask(long, long, long, long, long, long) line: 5578	
	Display.applicationProc(long, long, long, long, long, long) line: 5979	
	OS.objc_msgSend(long, long, long, long, long, boolean) line: not available [native method]	
	NSApplication.nextEventMatchingMask(long, NSDate, NSString, boolean) line: 92	
	Display.readAndDispatch() line: 3997	
	PartRenderingEngine$5.run() line: 1151	
	Realm.runWithDefault(Realm, Runnable) line: 339	
	PartRenderingEngine.run(MApplicationElement, IEclipseContext) line: 1042	
	E4Workbench.createAndRunUI(MApplicationElement) line: 153	
	Workbench.lambda$3(Display, WorkbenchAdvisor, int[]) line: 668	
	0x00000008002b97b8.run() line: not available	
	Realm.runWithDefault(Realm, Runnable) line: 339	
	Workbench.createAndRunWorkbench(Display, WorkbenchAdvisor) line: 576	
	PlatformUI.createAndRunWorkbench(Display, WorkbenchAdvisor) line: 173	
	IDEApplication.start(IApplicationContext) line: 178	
	EclipseAppHandle.run(Object) line: 208	
	EclipseAppLauncher.runApplication(Object) line: 149	
	EclipseAppLauncher.start(Object) line: 115	
	EclipseStarter.run(Object) line: 467	
	EclipseStarter.run(String[], Runnable) line: 298	
	DirectMethodHandle$Holder.invokeStatic(Object, Object, Object) line: not available	
	0x00000008000c6800.invoke(Object, Object, Object, Object) line: not available	
	0x00000008000c6c00.invokeExact_MT(Object, Object, Object, Object, Object) line: not available	
	DirectMethodHandleAccessor.invokeImpl(Object, Object[]) line: 155	
	DirectMethodHandleAccessor.invoke(Object, Object[]) line: 103	
	Method.invoke(Object, Object...) line: 580	
	Main.invokeFramework(String[], URL[]) line: 670	
	Main.basicRun(String[]) line: 607	
	Main.run(String[]) line: 1492	
	Main.main(String[]) line: 1465	
```

**Comment by basilevs** [comment]
Fixed

**Comment by basilevs** [comment]
This was not really fixed. The problem is caused by https://github.com/eclipse-platform/eclipse.platform.ui/issues/3920

It can be reproduced when starting AUT in a JVM that is built on latest MacOS SDK (for example 26.x).
The bug is in SWT, RCPTT probably should not do much here.
