### ISSUE TITLE
A sleeping job is being waited for too long

### ISSUE THREAD

**Issue by basilevs** [eclipse-rcptt/org.eclipse.rcptt#65]
A sleeping job may get stuck in an active state until the major timeout.
See test AssertionOfWholeTableWithoutColumnsCase2 in a [report](https://ci.eclipse.org/rcptt/view/active/job/master/1737/artifact/rcpttTests/target/results/tests.html) 

The potential cause is that when UIJobCollector is enabled, it finds existing jobs, but can't detect their schedule.
Then it thinks a job is scheduled for an immediate execution and waits for it indefinitely.

**Comment by basilevs** [comment]
More tests have revealed, that UIJobCollector does not wait for listener completion before dismissing a job. This is fixed in a branch with a reflection hack.

**Comment by basilevs** [comment]
```

!ENTRY org.eclipse.rcptt.tesla.core 4 0 2024-04-13 19:49:31.166
!MESSAGE org.eclipse.core.internal.jobs.JobListeners.waitAndSendEvents(org.eclipse.core.internal.jobs.InternalJob,boolean)
!STACK 0
java.lang.NoSuchMethodException: org.eclipse.core.internal.jobs.JobListeners.waitAndSendEvents(org.eclipse.core.internal.jobs.InternalJob,boolean)
	at java.base/java.lang.Class.getDeclaredMethod(Class.java:2613)
	at org.eclipse.rcptt.tesla.internal.ui.player.TeslaSWTAccess.callMethod(TeslaSWTAccess.java:410)
	at org.eclipse.rcptt.tesla.internal.ui.player.TeslaSWTAccess.waitListeners(TeslaSWTAccess.java:657)
	at org.eclipse.rcptt.tesla.internal.ui.player.UIJobCollector$1.run(UIJobCollector.java:252)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by basilevs** [comment]
```
!ENTRY org.eclipse.core.jobs 4 2 2024-04-14 10:02:24.402
!MESSAGE IJobChangeListener timeout detected. Further calls to IJobChangeListener may occur in random order and join(family) can return too soon. IJobChangeListener should return within 3000 ms. IJobChangeListener methods should not block. Possible deadlock.
!STACK 0
java.util.concurrent.TimeoutException: IJobChangeListener timeout detected. Further calls to IJobChangeListener may occur in random order and join(family) can return too soon. IJobChangeListener should return within 3000 ms. IJobChangeListener methods should not block. Possible deadlock.
	at org.eclipse.core.internal.jobs.JobListeners.waitAndSendEvents(JobListeners.java:106)
	at org.eclipse.core.internal.jobs.JobManager.startJob(JobManager.java:1774)
	at org.eclipse.core.internal.jobs.WorkerPool.startJob(WorkerPool.java:244)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:58)
!SUBENTRY 1 org.eclipse.core.jobs 4 2 2024-04-14 10:02:24.403
!MESSAGE Thread that is running the IJobChangeListener: Worker-2: Indexing in progress...
	at org.eclipse.rcptt.tesla.internal.ui.player.UIJobCollector.scheduled(UIJobCollector.java:340)
	at org.eclipse.core.internal.jobs.JobListeners$$Lambda$152/0x00000008011f8c80.notify(Unknown Source)
	at org.eclipse.core.internal.jobs.JobListeners.sendEvent(JobListeners.java:153)
	at org.eclipse.core.internal.jobs.JobListeners.sendEventsAsync(JobListeners.java:140)
	at org.eclipse.core.internal.jobs.JobListeners.waitAndSendEvents(JobListeners.java:80)
	at org.eclipse.core.internal.jobs.JobManager.withWriteLock(JobManager.java:549)
	at org.eclipse.core.internal.jobs.JobManager.schedule(JobManager.java:1395)
	at org.eclipse.core.internal.jobs.InternalJob.schedule(InternalJob.java:396)
	at org.eclipse.core.runtime.jobs.Job.schedule(Job.java:654)
	at org.eclipse.rcptt.tesla.internal.ui.player.UIJobCollector.done(UIJobCollector.java:329)
	at org.eclipse.core.internal.jobs.JobListeners$$Lambda$150/0x00000008011f8840.notify(Unknown Source)
	at org.eclipse.core.internal.jobs.JobListeners.sendEvent(JobListeners.java:153)
	at org.eclipse.core.internal.jobs.JobListeners.sendEventsAsync(JobListeners.java:140)
	at org.eclipse.core.internal.jobs.JobListeners.waitAndSendEvents(JobListeners.java:80)
	at org.eclipse.core.internal.jobs.JobManager.withWriteLock(JobManager.java:549)
	at org.eclipse.core.internal.jobs.JobManager.endJob(JobManager.java:750)
	at org.eclipse.core.internal.jobs.WorkerPool.endJob(WorkerPool.java:117)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:83)
```

**Comment by basilevs** [comment]
This is probably fixed
