### ISSUE TITLE
Eclipse plugin - NoSuchMethodError in 2024-12 (4.34)

### ISSUE THREAD

**Issue by benken-parasoft** [eclipse-rcptt/org.eclipse.rcptt#96]
Install the RCPTT 2.5.5 Eclipse plugin into Eclipse 2024-12 (4.34).  Running an AUT launch configuration fails with the following error:
```
java.lang.NoSuchMethodError: 'java.net.URI[] org.eclipse.pde.internal.core.target.IUBundleContainer.getRepositories()'
	at org.eclipse.rcptt.launching.ext.Q7ExternalLaunchDelegate.isQ7BundleContainer(Q7ExternalLaunchDelegate.java:764)
	at org.eclipse.rcptt.launching.configuration.Q7LaunchConfigurationDelegate.preLaunchCheck(Q7LaunchConfigurationDelegate.java:285)
	at org.eclipse.pde.launching.AbstractPDELaunchConfiguration.launch(AbstractPDELaunchConfiguration.java:140)
	at org.eclipse.rcptt.launching.configuration.Q7LaunchConfigurationDelegate.launch(Q7LaunchConfigurationDelegate.java:93)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:777)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:688)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1054)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$1.run(DebugUIPlugin.java:1257)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

The method signature for `org.eclipse.pde.internal.core.target.IUBundleContainer.getRepositories()` was recently changed to return a List instead of an array: https://github.com/eclipse-pde/eclipse.pde/commit/33efe8c6a98d83edfd9df33b3d613cb853929bb3

**Comment by benken-parasoft** [comment]
I confirmed that the launch works again after changing that one line in `isQ7BundleContainer`:
```
-               URI[] uris = ((IUBundleContainer) container).getRepositories();
+               List<URI> uris = ((IUBundleContainer) container).getRepositories();
```

**Comment by benken-parasoft** [comment]
I still see the issue in 2.6.0.202503091020.  Will a newer "nightly" build be available soon with the fix?

**Comment by basilevs** [comment]
> I still see the issue in 2.6.0.202503091020. Will a newer "nightly" build be available soon with the fix?

Yes, in a sense, that it will become available once build system recovers from various infrastructure problems.

I've started another nightly build to see if it has recovered enough.

**Comment by basilevs** [comment]
> I've started another nightly build to see if it has recovered enough.

Nope, this time license database has failed.

**Comment by alirana01** [comment]
v2.6.0 isn't compatible wtih eclipse 2025-06 as I am unable to install the plugin without removing the PDE integration
Any idea on this fix?

**Comment by benken-parasoft** [comment]
> v2.6.0 isn't compatible wtih eclipse 2025-06

For 2025-06 you have to use the 2.7.0 nightly build.  It has been working just fine for me.
